import type { ArtifactDraft, Platform } from "./types.js";

export interface TopicSignal {
  source: string;
  platform: Platform;
  keyword: string;
  strength: number;
  evidenceUrl?: string;
  collectedAt?: string;
}

export interface TopicScore {
  audienceReach: number;
  visualFeasibility: number;
  productionCostEfficiency: number;
  novelty: number;
  monetization: number;
  seriesPotential: number;
  complianceRisk: number;
  final: number;
}

export interface TopicCandidate {
  id: string;
  platform: Platform;
  track: string;
  audience: string;
  painPoint: string;
  hook: string;
  evidence: TopicSignal[];
  score: TopicScore;
  status: "draft" | "shortlisted" | "approved" | "rejected" | "tested";
}

export interface TopicScoringInput {
  platform: Platform;
  track: string;
  audience: string;
  painPoint: string;
  hook: string;
  evidence: TopicSignal[];
  audienceReach: number;
  visualFeasibility: number;
  productionCostEfficiency: number;
  novelty: number;
  monetization: number;
  seriesPotential: number;
  complianceRisk: number;
}

export interface TopicScoringWeights {
  audienceReach: number;
  visualFeasibility: number;
  productionCostEfficiency: number;
  novelty: number;
  monetization: number;
  seriesPotential: number;
  complianceSafety: number;
}

export const defaultTopicScoringWeights: TopicScoringWeights = {
  audienceReach: 0.18,
  visualFeasibility: 0.14,
  productionCostEfficiency: 0.14,
  novelty: 0.14,
  monetization: 0.12,
  seriesPotential: 0.18,
  complianceSafety: 0.1,
};

export function scoreTopicCandidate(
  id: string,
  input: TopicScoringInput,
  weights: TopicScoringWeights = defaultTopicScoringWeights,
): TopicCandidate {
  const score: TopicScore = {
    audienceReach: clampScore(input.audienceReach),
    visualFeasibility: clampScore(input.visualFeasibility),
    productionCostEfficiency: clampScore(input.productionCostEfficiency),
    novelty: clampScore(input.novelty),
    monetization: clampScore(input.monetization),
    seriesPotential: clampScore(input.seriesPotential),
    complianceRisk: clampScore(input.complianceRisk),
    final: 0,
  };

  score.final = roundScore(
    score.audienceReach * weights.audienceReach +
      score.visualFeasibility * weights.visualFeasibility +
      score.productionCostEfficiency * weights.productionCostEfficiency +
      score.novelty * weights.novelty +
      score.monetization * weights.monetization +
      score.seriesPotential * weights.seriesPotential +
      (100 - score.complianceRisk) * weights.complianceSafety,
  );

  return {
    id,
    platform: input.platform,
    track: input.track,
    audience: input.audience,
    painPoint: input.painPoint,
    hook: input.hook,
    evidence: input.evidence,
    score,
    status: score.final >= 70 && score.complianceRisk < 65 ? "shortlisted" : "draft",
  };
}

export function topicCandidateArtifact(candidate: TopicCandidate): ArtifactDraft<TopicCandidate> {
  return {
    kind: "topic_candidate",
    data: candidate,
    provenance: {
      providerId: "topic-intelligence",
      notes: "Generated by Topic Intelligence Engine scoring.",
    },
  };
}

function clampScore(value: number): number {
  if (!Number.isFinite(value)) {
    return 0;
  }

  return Math.max(0, Math.min(100, value));
}

function roundScore(value: number): number {
  return Math.round(value * 10) / 10;
}
